input {
  http {
    host => "0.0.0.0"
    port => 8080
    codec => json
  }
}

filter {
  mutate {
    add_field => {
      "[edr][ingest_source]" => "logstash-http"
      "[event][dataset]" => "edr.raw"
    }
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "edr-raw-events-%{+YYYY.MM.dd}"
  }

  stdout {
    codec => rubydebug
  }
}
